name: CD - Deploy to Azure VM

on:
  push:
    branches:
      - test_branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}

          script: |
            set -e

            echo "Changing to project directory"
            cd end-to-end-project

            echo "Fetching latest code"
            git fetch origin
            git reset --hard origin/test_branch

            echo "Stopping old containers"
            docker-compose down

            echo "Building fresh image (no cache)"
            docker-compose build --no-cache

            echo "Starting containers"
            docker-compose up -d

            echo "Verifying application"
            curl http://localhost/health

            



